#!/usr/bin/env python3
"""
Build a single self-contained klusraak-demo.html from frontend/public/.

Inlines styles.css and every <script src="..."> into the document so the
result can be opened directly from disk (file:// URL) on any device. Kept
external: Google Fonts and Lucide icons CDN — both still resolve when
the user has internet, and inlining them would 10x the file size.

Usage:
    python3 scripts/build-standalone.py
    # → produces ./klusraak-demo.html at repo root
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "frontend" / "public"
OUT = ROOT / "klusraak-demo.html"


def main() -> None:
    html = (SRC / "index.html").read_text(encoding="utf-8")
    css = (SRC / "css" / "styles.css").read_text(encoding="utf-8")

    # Inline the stylesheet (matches both <link rel="stylesheet" href="css/styles.css">
    # and the cache-busted variant href="css/styles.css?v=N").
    html = re.sub(
        r'<link\s+rel="stylesheet"\s+href="css/styles\.css(\?v=\d+)?"\s*/?>',
        f"<style>\n{css}\n</style>",
        html,
        count=1,
    )

    # Force demo-mode on by default — the standalone file has no real backend
    # behind it, so we want the mock API active without requiring ?demo=1.
    html = html.replace(
        "</head>",
        '<script>window.KLUSRAAK_FORCE_DEMO=true;localStorage.setItem("klusraak.demo","1");</script>\n</head>',
        1,
    )

    # Inline every <script src="js/..."> tag in the order they appear.
    def replace_script(match: re.Match[str]) -> str:
        rel = match.group(1)
        # strip any ?v=... cache-buster
        rel_clean = rel.split("?")[0]
        path = SRC / rel_clean
        if not path.exists():
            return match.group(0)  # leave unknown sources alone
        body = path.read_text(encoding="utf-8")
        return f"<script>\n/* === inlined: {rel_clean} === */\n{body}\n</script>"

    html = re.sub(
        r'<script\s+src="(js/[^"]+)"\s*></script>',
        replace_script,
        html,
    )

    # Add a banner at the top of <body> so the user knows this is the
    # standalone, file:// build (helpful when sharing).
    html = html.replace(
        "<body>",
        '<body>\n<!-- Klusraak standalone demo — generated by scripts/build-standalone.py -->',
        1,
    )

    OUT.write_text(html, encoding="utf-8")
    size_kb = OUT.stat().st_size / 1024
    print(f"✅ wrote {OUT.relative_to(ROOT)} ({size_kb:.1f} KB)")


if __name__ == "__main__":
    main()
